import { Configure, GenericTypeGuard, GenericValidator } from 'runtime-typescript-checker'
import { ConstrucorOption, SendImageParam, SendTextParam, SendVideoParam, SendAudioParam, SendLocationParam, SendContactParam, SendStickerParam, SendTemplateParam, SendProductParam, SendProductListParam } from './outbound'

// ** THIS FILE IS AUTOGENERATED; DO NOT CHANGE.

export { Configure }

export function ValidateConstrucorOption (iCandidate: unknown): ReturnType<typeof GenericValidator> {
  return GenericValidator('ConstrucorOption', iCandidate)
}

export function IsConstrucorOption (iCandidate: unknown): iCandidate is ConstrucorOption {
  return GenericTypeGuard('ConstrucorOption', iCandidate)
}

export function ValidateSendImageParam (iCandidate: unknown): ReturnType<typeof GenericValidator> {
  return GenericValidator('SendImageParam', iCandidate)
}

export function IsSendImageParam (iCandidate: unknown): iCandidate is SendImageParam {
  return GenericTypeGuard('SendImageParam', iCandidate)
}

export function ValidateSendTextParam (iCandidate: unknown): ReturnType<typeof GenericValidator> {
  return GenericValidator('SendTextParam', iCandidate)
}

export function IsSendTextParam (iCandidate: unknown): iCandidate is SendTextParam {
  return GenericTypeGuard('SendTextParam', iCandidate)
}

export function ValidateSendVideoParam (iCandidate: unknown): ReturnType<typeof GenericValidator> {
  return GenericValidator('SendVideoParam', iCandidate)
}

export function IsSendVideoParam (iCandidate: unknown): iCandidate is SendVideoParam {
  return GenericTypeGuard('SendVideoParam', iCandidate)
}

export function ValidateSendAudioParam (iCandidate: unknown): ReturnType<typeof GenericValidator> {
  return GenericValidator('SendAudioParam', iCandidate)
}

export function IsSendAudioParam (iCandidate: unknown): iCandidate is SendAudioParam {
  return GenericTypeGuard('SendAudioParam', iCandidate)
}

export function ValidateSendLocationParam (iCandidate: unknown): ReturnType<typeof GenericValidator> {
  return GenericValidator('SendLocationParam', iCandidate)
}

export function IsSendLocationParam (iCandidate: unknown): iCandidate is SendLocationParam {
  return GenericTypeGuard('SendLocationParam', iCandidate)
}

export function ValidateSendContactParam (iCandidate: unknown): ReturnType<typeof GenericValidator> {
  return GenericValidator('SendContactParam', iCandidate)
}

export function IsSendContactParam (iCandidate: unknown): iCandidate is SendContactParam {
  return GenericTypeGuard('SendContactParam', iCandidate)
}

export function ValidateSendStickerParam (iCandidate: unknown): ReturnType<typeof GenericValidator> {
  return GenericValidator('SendStickerParam', iCandidate)
}

export function IsSendStickerParam (iCandidate: unknown): iCandidate is SendStickerParam {
  return GenericTypeGuard('SendStickerParam', iCandidate)
}

export function ValidateSendTemplateParam (iCandidate: unknown): ReturnType<typeof GenericValidator> {
  return GenericValidator('SendTemplateParam', iCandidate)
}

export function IsSendTemplateParam (iCandidate: unknown): iCandidate is SendTemplateParam {
  return GenericTypeGuard('SendTemplateParam', iCandidate)
}

export function ValidateSendProductParam (iCandidate: unknown): ReturnType<typeof GenericValidator> {
  return GenericValidator('SendProductParam', iCandidate)
}

export function IsSendProductParam (iCandidate: unknown): iCandidate is SendProductParam {
  return GenericTypeGuard('SendProductParam', iCandidate)
}

export function ValidateSendProductListParam (iCandidate: unknown): ReturnType<typeof GenericValidator> {
  return GenericValidator('SendProductListParam', iCandidate)
}

export function IsSendProductListParam (iCandidate: unknown): iCandidate is SendProductListParam {
  return GenericTypeGuard('SendProductListParam', iCandidate)
}
