import { Configure, GenericTypeGuard, GenericValidator } from 'runtime-typescript-checker';
import { ConstructorOptions, UploadFile, DeleteMedia, DownloadFile, GetMediaUrl } from './media';

// ** THIS FILE IS AUTOGENERATED; DO NOT CHANGE.

export { Configure };

export function ValidateConstructorOptions(iCandidate: unknown): ReturnType<typeof GenericValidator> {
   return GenericValidator("ConstructorOptions", iCandidate);
}

export function IsConstructorOptions(iCandidate: unknown): iCandidate is ConstructorOptions {
   return GenericTypeGuard("ConstructorOptions", iCandidate);
}

export function ValidateUploadFile(iCandidate: unknown): ReturnType<typeof GenericValidator> {
   return GenericValidator("UploadFile", iCandidate);
}

export function IsUploadFile(iCandidate: unknown): iCandidate is UploadFile {
   return GenericTypeGuard("UploadFile", iCandidate);
}

export function ValidateDeleteMedia(iCandidate: unknown): ReturnType<typeof GenericValidator> {
   return GenericValidator("DeleteMedia", iCandidate);
}

export function IsDeleteMedia(iCandidate: unknown): iCandidate is DeleteMedia {
   return GenericTypeGuard("DeleteMedia", iCandidate);
}

export function ValidateDownloadFile(iCandidate: unknown): ReturnType<typeof GenericValidator> {
   return GenericValidator("DownloadFile", iCandidate);
}

export function IsDownloadFile(iCandidate: unknown): iCandidate is DownloadFile {
   return GenericTypeGuard("DownloadFile", iCandidate);
}

export function ValidateGetMediaUrl(iCandidate: unknown): ReturnType<typeof GenericValidator> {
   return GenericValidator("GetMediaUrl", iCandidate);
}

export function IsGetMediaUrl(iCandidate: unknown): iCandidate is GetMediaUrl {
   return GenericTypeGuard("GetMediaUrl", iCandidate);
}
