import { Configure, GenericTypeGuard, GenericValidator } from 'runtime-typescript-checker';
import { ConstructorOptions, GetProfile, UpdateProfile, RequestPhoneVerification, VerifyPhone, GetPhoneNumbers, GetPhoneNumbersByFilter, GetDisplayStatus, AddPhoneNumber, getPhoneCertificate, getPhoneOtpStatus } from './account';

// ** THIS FILE IS AUTOGENERATED; DO NOT CHANGE.

export { Configure };

export function ValidateConstructorOptions(iCandidate: unknown): ReturnType<typeof GenericValidator> {
   return GenericValidator("ConstructorOptions", iCandidate);
}

export function IsConstructorOptions(iCandidate: unknown): iCandidate is ConstructorOptions {
   return GenericTypeGuard("ConstructorOptions", iCandidate);
}

export function ValidateGetProfile(iCandidate: unknown): ReturnType<typeof GenericValidator> {
   return GenericValidator("GetProfile", iCandidate);
}

export function IsGetProfile(iCandidate: unknown): iCandidate is GetProfile {
   return GenericTypeGuard("GetProfile", iCandidate);
}

export function ValidateUpdateProfile(iCandidate: unknown): ReturnType<typeof GenericValidator> {
   return GenericValidator("UpdateProfile", iCandidate);
}

export function IsUpdateProfile(iCandidate: unknown): iCandidate is UpdateProfile {
   return GenericTypeGuard("UpdateProfile", iCandidate);
}

export function ValidateRequestPhoneVerification(iCandidate: unknown): ReturnType<typeof GenericValidator> {
   return GenericValidator("RequestPhoneVerification", iCandidate);
}

export function IsRequestPhoneVerification(iCandidate: unknown): iCandidate is RequestPhoneVerification {
   return GenericTypeGuard("RequestPhoneVerification", iCandidate);
}

export function ValidateVerifyPhone(iCandidate: unknown): ReturnType<typeof GenericValidator> {
   return GenericValidator("VerifyPhone", iCandidate);
}

export function IsVerifyPhone(iCandidate: unknown): iCandidate is VerifyPhone {
   return GenericTypeGuard("VerifyPhone", iCandidate);
}

export function ValidateGetPhoneNumbers(iCandidate: unknown): ReturnType<typeof GenericValidator> {
   return GenericValidator("GetPhoneNumbers", iCandidate);
}

export function IsGetPhoneNumbers(iCandidate: unknown): iCandidate is GetPhoneNumbers {
   return GenericTypeGuard("GetPhoneNumbers", iCandidate);
}

export function ValidateGetPhoneNumbersByFilter(iCandidate: unknown): ReturnType<typeof GenericValidator> {
   return GenericValidator("GetPhoneNumbersByFilter", iCandidate);
}

export function IsGetPhoneNumbersByFilter(iCandidate: unknown): iCandidate is GetPhoneNumbersByFilter {
   return GenericTypeGuard("GetPhoneNumbersByFilter", iCandidate);
}

export function ValidateGetDisplayStatus(iCandidate: unknown): ReturnType<typeof GenericValidator> {
   return GenericValidator("GetDisplayStatus", iCandidate);
}

export function IsGetDisplayStatus(iCandidate: unknown): iCandidate is GetDisplayStatus {
   return GenericTypeGuard("GetDisplayStatus", iCandidate);
}

export function ValidateAddPhoneNumber(iCandidate: unknown): ReturnType<typeof GenericValidator> {
   return GenericValidator("AddPhoneNumber", iCandidate);
}

export function IsAddPhoneNumber(iCandidate: unknown): iCandidate is AddPhoneNumber {
   return GenericTypeGuard("AddPhoneNumber", iCandidate);
}

export function ValidategetPhoneCertificate(iCandidate: unknown): ReturnType<typeof GenericValidator> {
   return GenericValidator("getPhoneCertificate", iCandidate);
}

export function IsgetPhoneCertificate(iCandidate: unknown): iCandidate is getPhoneCertificate {
   return GenericTypeGuard("getPhoneCertificate", iCandidate);
}

export function ValidategetPhoneOtpStatus(iCandidate: unknown): ReturnType<typeof GenericValidator> {
   return GenericValidator("getPhoneOtpStatus", iCandidate);
}

export function IsgetPhoneOtpStatus(iCandidate: unknown): iCandidate is getPhoneOtpStatus {
   return GenericTypeGuard("getPhoneOtpStatus", iCandidate);
}
